/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsFabricRouteImport } from './routes/projects.fabric'
import { Route as ProjectsDatabricksRouteImport } from './routes/projects.databricks'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as ProjectsFabricIndexRouteImport } from './routes/projects.fabric.index'
import { Route as ProjectsDatabricksIndexRouteImport } from './routes/projects.databricks.index'
import { Route as ProjectsFabricNorthMeridianRouteImport } from './routes/projects.fabric.north-meridian'
import { Route as ProjectsFabricIdRouteImport } from './routes/projects.fabric.$id'
import { Route as ProjectsDatabricksIdRouteImport } from './routes/projects.databricks.$id'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFabricRoute = ProjectsFabricRouteImport.update({
  id: '/projects/fabric',
  path: '/projects/fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDatabricksRoute = ProjectsDatabricksRouteImport.update({
  id: '/projects/databricks',
  path: '/projects/databricks',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFabricIndexRoute = ProjectsFabricIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsFabricRoute,
} as any)
const ProjectsDatabricksIndexRoute = ProjectsDatabricksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsDatabricksRoute,
} as any)
const ProjectsFabricNorthMeridianRoute =
  ProjectsFabricNorthMeridianRouteImport.update({
    id: '/north-meridian',
    path: '/north-meridian',
    getParentRoute: () => ProjectsFabricRoute,
  } as any)
const ProjectsFabricIdRoute = ProjectsFabricIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsFabricRoute,
} as any)
const ProjectsDatabricksIdRoute = ProjectsDatabricksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsDatabricksRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/projects/databricks': typeof ProjectsDatabricksRouteWithChildren
  '/projects/fabric': typeof ProjectsFabricRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/projects/databricks/$id': typeof ProjectsDatabricksIdRoute
  '/projects/fabric/$id': typeof ProjectsFabricIdRoute
  '/projects/fabric/north-meridian': typeof ProjectsFabricNorthMeridianRoute
  '/projects/databricks/': typeof ProjectsDatabricksIndexRoute
  '/projects/fabric/': typeof ProjectsFabricIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/projects/databricks/$id': typeof ProjectsDatabricksIdRoute
  '/projects/fabric/$id': typeof ProjectsFabricIdRoute
  '/projects/fabric/north-meridian': typeof ProjectsFabricNorthMeridianRoute
  '/projects/databricks': typeof ProjectsDatabricksIndexRoute
  '/projects/fabric': typeof ProjectsFabricIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/projects/databricks': typeof ProjectsDatabricksRouteWithChildren
  '/projects/fabric': typeof ProjectsFabricRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/projects/databricks/$id': typeof ProjectsDatabricksIdRoute
  '/projects/fabric/$id': typeof ProjectsFabricIdRoute
  '/projects/fabric/north-meridian': typeof ProjectsFabricNorthMeridianRoute
  '/projects/databricks/': typeof ProjectsDatabricksIndexRoute
  '/projects/fabric/': typeof ProjectsFabricIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies/$slug'
    | '/projects/databricks'
    | '/projects/fabric'
    | '/api/public/contact'
    | '/projects/databricks/$id'
    | '/projects/fabric/$id'
    | '/projects/fabric/north-meridian'
    | '/projects/databricks/'
    | '/projects/fabric/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies/$slug'
    | '/api/public/contact'
    | '/projects/databricks/$id'
    | '/projects/fabric/$id'
    | '/projects/fabric/north-meridian'
    | '/projects/databricks'
    | '/projects/fabric'
  id:
    | '__root__'
    | '/'
    | '/case-studies/$slug'
    | '/projects/databricks'
    | '/projects/fabric'
    | '/api/public/contact'
    | '/projects/databricks/$id'
    | '/projects/fabric/$id'
    | '/projects/fabric/north-meridian'
    | '/projects/databricks/'
    | '/projects/fabric/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  ProjectsDatabricksRoute: typeof ProjectsDatabricksRouteWithChildren
  ProjectsFabricRoute: typeof ProjectsFabricRouteWithChildren
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fabric': {
      id: '/projects/fabric'
      path: '/projects/fabric'
      fullPath: '/projects/fabric'
      preLoaderRoute: typeof ProjectsFabricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/databricks': {
      id: '/projects/databricks'
      path: '/projects/databricks'
      fullPath: '/projects/databricks'
      preLoaderRoute: typeof ProjectsDatabricksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fabric/': {
      id: '/projects/fabric/'
      path: '/'
      fullPath: '/projects/fabric/'
      preLoaderRoute: typeof ProjectsFabricIndexRouteImport
      parentRoute: typeof ProjectsFabricRoute
    }
    '/projects/databricks/': {
      id: '/projects/databricks/'
      path: '/'
      fullPath: '/projects/databricks/'
      preLoaderRoute: typeof ProjectsDatabricksIndexRouteImport
      parentRoute: typeof ProjectsDatabricksRoute
    }
    '/projects/fabric/north-meridian': {
      id: '/projects/fabric/north-meridian'
      path: '/north-meridian'
      fullPath: '/projects/fabric/north-meridian'
      preLoaderRoute: typeof ProjectsFabricNorthMeridianRouteImport
      parentRoute: typeof ProjectsFabricRoute
    }
    '/projects/fabric/$id': {
      id: '/projects/fabric/$id'
      path: '/$id'
      fullPath: '/projects/fabric/$id'
      preLoaderRoute: typeof ProjectsFabricIdRouteImport
      parentRoute: typeof ProjectsFabricRoute
    }
    '/projects/databricks/$id': {
      id: '/projects/databricks/$id'
      path: '/$id'
      fullPath: '/projects/databricks/$id'
      preLoaderRoute: typeof ProjectsDatabricksIdRouteImport
      parentRoute: typeof ProjectsDatabricksRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsDatabricksRouteChildren {
  ProjectsDatabricksIdRoute: typeof ProjectsDatabricksIdRoute
  ProjectsDatabricksIndexRoute: typeof ProjectsDatabricksIndexRoute
}

const ProjectsDatabricksRouteChildren: ProjectsDatabricksRouteChildren = {
  ProjectsDatabricksIdRoute: ProjectsDatabricksIdRoute,
  ProjectsDatabricksIndexRoute: ProjectsDatabricksIndexRoute,
}

const ProjectsDatabricksRouteWithChildren =
  ProjectsDatabricksRoute._addFileChildren(ProjectsDatabricksRouteChildren)

interface ProjectsFabricRouteChildren {
  ProjectsFabricIdRoute: typeof ProjectsFabricIdRoute
  ProjectsFabricNorthMeridianRoute: typeof ProjectsFabricNorthMeridianRoute
  ProjectsFabricIndexRoute: typeof ProjectsFabricIndexRoute
}

const ProjectsFabricRouteChildren: ProjectsFabricRouteChildren = {
  ProjectsFabricIdRoute: ProjectsFabricIdRoute,
  ProjectsFabricNorthMeridianRoute: ProjectsFabricNorthMeridianRoute,
  ProjectsFabricIndexRoute: ProjectsFabricIndexRoute,
}

const ProjectsFabricRouteWithChildren = ProjectsFabricRoute._addFileChildren(
  ProjectsFabricRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  ProjectsDatabricksRoute: ProjectsDatabricksRouteWithChildren,
  ProjectsFabricRoute: ProjectsFabricRouteWithChildren,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
